require 'i18n'
require 'json'
require 'pathname'
require 'singleton'
require 'sqlite3'
require 'yaml'

require_relative 'quiz_dorosh'
require_relative 'config'
require_relative 'question'
require_relative 'question_data'
require_relative 'file_writer'
require_relative 'input_reader'
require_relative 'statistics'
require_relative 'engine'

