- question: Які наслідки надмірного використання електронних пристроїв можуть виникати у зв'язку з інформаційною гігієною?
  answers:
    - Зменшення концентрації та погіршення пам'яті
    - Покращення соціальної взаємодії та розвиток комунікативних навичок
    - Збільшення фізичного здоров'я та енергії
    - Покращення сну та відновлення організму
- question: Які стратегії можуть бути використані для зниження інформаційного стресу?
  answers:
    - Обмеження часу, проведеного в онлайн-середовищі 
    - Збільшення обсягу інформації, що споживається 
    - Залучення до активного споживання інформації на всіх доступних платформах 
    - Ігнорування негативних впливів інформаційних потоків
- question: Які можливості забезпечуються розумним використанням інформаційних технологій? 
  answers:
    - Зручний доступ до інформації та ресурсів
    - Підвищення соціального рівня
    - Зменшення кількості інформаційних джерел 
    - Збільшення ізольованості та відсутність комунікації
  - question: Як можна розпізнати недостовірну інформацію та фейкові новини?
  answers:
    - Перевірка джерела та авторитетності інформації
    - Поширення інформації без перевірки достовірності 
    - Переконання, що всі новини в Інтернеті є правдивими 
    - Відсутність контролю над якістю інформації
- question: Які практики сприяють збереженню приватності та безпеки в інформаційному середовищі?
  answers:
    - Використання надійних паролів та регулярна їх зміна 
    - Обмеження розкриття особистої інформації в мережі Інтернет
    - Публічна розміщення всіх особистих даних в профілях соціальних мереж
    - Відмова від використання антивірусного програмного забезпечення
- question: Як можна розвивати критичне мислення та аналітичні навички в контексті інформаційної гігієни?
  answers:
    - Перевірка джерела та перехресна перевірка інформації
    - Прийняття всієї інформації без критичного осмислення
    - Відмова від висловлювання власної думки
    - Ігнорування протиріччя в інформації
- question: Які психологічні ефекти можуть виникати в результаті перенасиченості інформацією?
  answers:
    - Перенапруження та втома
    - Покращення пам'яті та когнітивних функцій
    - Відсутність емоційного впливу інформації
    - Збільшення творчості та інноваційного мислення
  